[build]
#target = "avr-atmega328p.json"
target = "avr-unknown-gnu-atmega328"

[unstable]
build-std = ["core"]

# -e main, run jump point
# -nostartfiles, no c runtime
# -T linker-script, isr
[target.'cfg(all(target_arch = "avr"))']
 rustflags = [
   "-Clink-args=-e main",
   "-Clink-args=-T tools/linker-script",# tools/interrupt_vector.S",
  #"-Clink-args=-T tools/linker-script tools/interrupt_vector.S",
  #"-Clink-args=-nostartfiles",
  #"-Clink-args=-nodefaultlibs",
  #"-Clink-args=-nolibc",
  #"-Clink-args=-nostdlib",
 ]
